### ISSUE TITLE
what

### ISSUE THREAD

**Issue by 4REW** [QuartzWarrior/UnbelievaBoat-AUTO#1]
![image](https://github.com/QuartzWarrior/UnbelievaBoat-AUTO/assets/89364610/fcd2e96c-94a1-4bd7-9190-d23e5b9fbafb)

**Comment by QuartzWarrior** [comment]
might have to try `python -m pip install -U -r requirements.txt`, or if that doesn't work, `py -m pip install -U -r requirements.txt`

**Comment by 4REW** [comment]
Still didnt work. same error

**Comment by 4REW** [comment]
nvm found fix

**Comment by 4REW** [comment]
![image](https://github.com/QuartzWarrior/UnbelievaBoat-AUTO/assets/89364610/a99c604d-2e26-4001-9b1f-fcb19f80a04c)
guess not. main python file wont open (instant close)

**Comment by QuartzWarrior** [comment]
@4REW 💀 that means your token is invalid
